doctrine:
    dbal:
        dbname:               ma_valise
        host:                 localhost
        port:                 3306
        user:                 root
        password:
        driver:               pdo_mysql
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
